### ISSUE TITLE
[Tips pages] Back to Top links

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#337] opened 2017-08-17 18:13 UTC
This comment came into Editors list <https://lists.w3.org/Archives/Public/wai-eo-editors/2017Aug/0006.html>

> A link to return to the top of the page would be very useful. Since there is not one, I have to scroll all the way back up, and hope that the side bar has not changed as I read pages.

**Comment by bakkenb** [comment] 2017-08-18 21:13
This feedback should be forwarded to the redesign task force so that it can be properly and consistently addressed in the redesign site.

**Comment by slhenry** [comment] 2017-09-15 20:07
I strongly suggest that we implement these with the redesign -- and if possible, before the usability testing -- especially because from the home page we will be linking into the middle of the Tips pages.

**Comment by yatil** [comment] 2017-09-15 20:21
The new design only has one back to top link that is displayed on the bottom of the viewport all the time (in line with the best practices here: https://www.nngroup.com/articles/back-to-top/). I don’t see the need for multiple back to top links as screen reader users can use either landmark navigation or built-in to top functionality and visual users have the button present all the time.

Feel free to close this issue.

**Comment by yatil** [comment] 2017-10-18 11:58
Of course, I’m happy to add another template for back to top links, if we want to do it.

**Comment by yatil** [comment] 2017-10-18 12:04
Duplicate of #308

**Comment by yatil** [comment] 2019-02-07 12:16
Obsolete

**Closed by yatil** 2019-02-07 12:16 UTC
Labels: wai-redesign-before
